# OSAL sys 模块源文件
obj-y += osal_clock.o
obj-y += osal_signal.o
obj-y += osal_file.o
obj-y += osal_select.o
obj-y += osal_env.o
obj-y += osal_time.o
obj-y += osal_process.o
obj-y += osal_thread.o
obj-y += osal_sched.o
