# SPDX-License-Identifier: GPL-2.0

lpf_runtime-$(CONFIG_LPF_MCU_SERVICE) += lpf-runtime/transport/mcu/lpf_mcu_transport.o
lpf_runtime-$(CONFIG_LPF_MCU_TRANSPORT_CAN) += lpf-runtime/transport/mcu/lpf_mcu_transport_can.o
lpf_runtime-$(CONFIG_LPF_MCU_TRANSPORT_UART) += lpf-runtime/transport/mcu/lpf_mcu_transport_uart.o
