# SPDX-License-Identifier: GPL-2.0

pdm_core-$(CONFIG_PDM_RUNTIME) += pdm-core/runtime/pdm_runtime.o
pdm_core-$(CONFIG_PDM_RUNTIME) += pdm-core/runtime/pdm_runtime_config.o
pdm_core-$(CONFIG_PDM_RUNTIME) += pdm-core/runtime/pdm_runtime_entry_start.o
