# SPDX-License-Identifier: GPL-2.0

lpf_peripheral_runtime-$(CONFIG_LPF_LED_SERVICE) += lpf/peripheral/led/lpf_led_service.o
lpf_peripheral_runtime-$(CONFIG_LPF_LED_SERVICE) += lpf/peripheral/led/lpf_led_chrdev.o
lpf_peripheral_runtime-$(CONFIG_LPF_LED_SERVICE) += lpf/peripheral/led/lpf_led_proc.o
