# SPDX-License-Identifier: GPL-2.0

# 已删除：pdm_mcu_config_driver.o - 静态配置已废弃，使用 Device Tree
pdm_core-$(CONFIG_PDM_MCU_SERVICE) += pdm-core/peripheral/mcu/pdm_mcu_service.o
pdm_core-$(CONFIG_PDM_MCU_SERVICE) += pdm-core/peripheral/mcu/pdm_mcu_chrdev.o
pdm_core-$(CONFIG_PDM_MCU_SERVICE) += pdm-core/peripheral/mcu/pdm_mcu_proc.o
pdm_core-$(CONFIG_PDM_MCU_SERVICE) += pdm-core/peripheral/mcu/pdm_mcu_transport.o
pdm_core-$(CONFIG_PDM_MCU_TRANSPORT_CAN) += pdm-core/peripheral/mcu/pdm_mcu_can.o
pdm_core-$(CONFIG_PDM_MCU_TRANSPORT_UART) += pdm-core/peripheral/mcu/pdm_mcu_uart.o
