# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_LPF_CORE) += lpf_core.o

include $(src)/lpf-core/core/Makefile
include $(src)/lpf-core/protocol/Makefile
include $(src)/lpf-core/compat/Makefile
include $(src)/lpf-core/soc/Makefile
