# SPDX-License-Identifier: GPL-2.0

lpf_runtime-y += lpf-runtime/runtime/lpf_runtime_module.o
lpf_runtime-y += lpf-runtime/runtime/lpf_runtime.o
lpf_runtime-y += lpf-runtime/runtime/lpf_runtime_config.o
lpf_runtime-y += lpf-runtime/runtime/lpf_runtime_entry_start.o
