# SPDX-License-Identifier: GPL-2.0

lpf_peripheral_runtime-$(CONFIG_LPF_MCU_SERVICE) += lpf/transport/mcu/lpf_mcu_transport.o
lpf_peripheral_runtime-$(CONFIG_LPF_MCU_TRANSPORT_CAN) += lpf/transport/mcu/lpf_mcu_transport_can.o
lpf_peripheral_runtime-$(CONFIG_LPF_MCU_TRANSPORT_UART) += lpf/transport/mcu/lpf_mcu_transport_uart.o
