# SPDX-License-Identifier: GPL-2.0

pdm_core-y += pdm-core/compat/pdm_compat_gpio.o
pdm_core-y += pdm-core/compat/pdm_compat_pwm.o
pdm_core-y += pdm-core/compat/pdm_compat_i2c.o
pdm_core-y += pdm-core/compat/pdm_compat_spi.o
pdm_core-y += pdm-core/compat/pdm_compat_can.o
pdm_core-y += pdm-core/compat/pdm_compat_serial.o
