# SPDX-License-Identifier: GPL-2.0

lpf_runtime-y += lpf/hw/lpf_hw.o
lpf_runtime-y += lpf/hw/lpf_hw_builtin_start.o
lpf_runtime-$(CONFIG_LPF_HW_CAN) += lpf/hw/lpf_hw_transport_can.o
lpf_runtime-$(CONFIG_LPF_HW_UART) += lpf/hw/lpf_hw_transport_uart.o
lpf_runtime-$(CONFIG_LPF_HW_GPIO) += lpf/hw/lpf_hw_gpio.o
lpf_runtime-$(CONFIG_LPF_HW_PWM) += lpf/hw/lpf_hw_pwm.o
lpf_runtime-$(CONFIG_LPF_HW_I2C) += lpf/hw/lpf_hw_bus_i2c.o
lpf_runtime-$(CONFIG_LPF_HW_SPI) += lpf/hw/lpf_hw_bus_spi.o
lpf_runtime-y += lpf/hw/lpf_hw_builtin_end.o
