# =============================================================================
# scripts/basic Makefile
# =============================================================================

hostprogs-y	:= fixdep

# fixdep is needed to compute auto.conf.cmd = dependency file
# The build rules are provided by scripts/Makefile.host

# Always build fixdep
.PHONY: $(hostprogs-y)
