# SPDX-License-Identifier: GPL-2.0

lpf_core-y += lpf-core/config/src/lpf_config_api.o
lpf_core-y += lpf-core/config/src/lpf_config_backend.o
lpf_core-y += lpf-core/config/src/lpf_config_dt_backend.o
lpf_core-y += lpf-core/config/src/lpf_config_dt_parser.o
lpf_core-y += lpf-core/config/src/lpf_config_static_backend.o
lpf_core-y += lpf-core/config/src/lpf_config_normalizer.o
lpf_core-y += lpf-core/config/src/lpf_config_validator.o
