# SPDX-License-Identifier: GPL-2.0

pdm_core-$(CONFIG_PDM_RUNTIME) += pdm-core/hw/core/pdm_hw.o
pdm_core-$(CONFIG_PDM_RUNTIME) += pdm-core/hw/core/pdm_hw_builtin_start.o
pdm_core-$(CONFIG_PDM_HW_CAN) += pdm-core/hw/can/pdm_hw_can.o
pdm_core-$(CONFIG_PDM_HW_UART) += pdm-core/hw/uart/pdm_hw_uart.o
pdm_core-$(CONFIG_PDM_HW_GPIO) += pdm-core/hw/gpio/pdm_hw_gpio.o
pdm_core-$(CONFIG_PDM_HW_PWM) += pdm-core/hw/pwm/pdm_hw_pwm.o
pdm_core-$(CONFIG_PDM_HW_I2C) += pdm-core/hw/i2c/pdm_hw_i2c.o
pdm_core-$(CONFIG_PDM_HW_SPI) += pdm-core/hw/spi/pdm_hw_spi.o
pdm_core-$(CONFIG_PDM_RUNTIME) += pdm-core/hw/core/pdm_hw_builtin_end.o
