# OSAL IPC 模块源文件（条件编译）
obj-$(CONFIG_OSAL_IPC) += osal_mutex.o
obj-$(CONFIG_OSAL_IPC) += osal_atomic.o
obj-$(CONFIG_OSAL_IPC) += osal_semaphore.o
obj-$(CONFIG_OSAL_IPC) += osal_cond.o
obj-$(CONFIG_OSAL_IPC) += osal_shm.o
