# HAL Linux 平台实现 - 条件编译

# 根据 Kconfig 配置选择驱动
obj-$(CONFIG_HAL_CAN) += hal_can_linux.o
obj-$(CONFIG_HAL_UART) += hal_serial_linux.o
obj-$(CONFIG_HAL_I2C) += hal_i2c_linux.o
obj-$(CONFIG_HAL_SPI) += hal_spi_linux.o
obj-$(CONFIG_HAL_GPIO) += hal_gpio_linux.o
obj-$(CONFIG_HAL_WATCHDOG) += hal_watchdog_linux.o
