# SPDX-License-Identifier: GPL-2.0

pdm_core-$(CONFIG_PDM_LED_SERVICE) += pdm-core/peripheral/led/pdm_led_config_driver.o
pdm_core-$(CONFIG_PDM_LED_SERVICE) += pdm-core/peripheral/led/pdm_led_service.o
pdm_core-$(CONFIG_PDM_LED_SERVICE) += pdm-core/peripheral/led/pdm_led_gpio.o
pdm_core-$(CONFIG_PDM_LED_SERVICE) += pdm-core/peripheral/led/pdm_led_pwm.o
pdm_core-$(CONFIG_PDM_LED_SERVICE) += pdm-core/peripheral/led/pdm_led_chrdev.o
pdm_core-$(CONFIG_PDM_LED_SERVICE) += pdm-core/peripheral/led/pdm_led_proc.o
