/************************************************************************
 * Kernel OSAL errno mapping
 ************************************************************************/

#ifndef OSAL_ERRNO_H
#define OSAL_ERRNO_H

#include <linux/errno.h>

#define OSAL_SUCCESS 0

#define OSAL_EPERM EPERM
#define OSAL_ENOENT ENOENT
#define OSAL_ESRCH ESRCH
#define OSAL_EINTR EINTR
#define OSAL_EIO EIO
#define OSAL_ENXIO ENXIO
#define OSAL_E2BIG E2BIG
#define OSAL_ENOEXEC ENOEXEC
#define OSAL_EBADF EBADF
#define OSAL_ECHILD ECHILD
#define OSAL_EAGAIN EAGAIN
#define OSAL_ENOMEM ENOMEM
#define OSAL_EACCES EACCES
#define OSAL_EFAULT EFAULT
#define OSAL_EBUSY EBUSY
#define OSAL_EEXIST EEXIST
#define OSAL_ENODEV ENODEV
#define OSAL_EINVAL EINVAL
#define OSAL_EMFILE EMFILE
#define OSAL_ENOSYS ENOSYS
#define OSAL_EWOULDBLOCK EWOULDBLOCK
#define OSAL_EPROTO EPROTO
#define OSAL_EOVERFLOW EOVERFLOW
#define OSAL_EOPNOTSUPP EOPNOTSUPP
#define OSAL_ETIMEDOUT ETIMEDOUT
#define OSAL_ECANCELED ECANCELED

#define OSAL_ERR_INVALID_POINTER OSAL_EFAULT
#define OSAL_ERR_NO_MEMORY OSAL_ENOMEM
#define OSAL_ERR_INVALID_SIZE OSAL_EINVAL
#define OSAL_ERR_INVALID_ID OSAL_EINVAL
#define OSAL_ERR_INVALID_PARAM OSAL_EINVAL
#define OSAL_ERR_NAME_TOO_LONG ENAMETOOLONG
#define OSAL_ERR_NAME_TAKEN OSAL_EEXIST
#define OSAL_ERR_NAME_NOT_FOUND OSAL_ENOENT
#define OSAL_ERR_TIMEOUT OSAL_ETIMEDOUT
#define OSAL_ERR_NOT_IMPLEMENTED OSAL_ENOSYS
#define OSAL_ERR_BUSY OSAL_EBUSY
#define OSAL_ERR_PERMISSION OSAL_EPERM
#define OSAL_ERR_NOT_SUPPORTED OSAL_EOPNOTSUPP
#define OSAL_ERR_ALREADY_EXISTS OSAL_EEXIST
#define OSAL_ERR_WOULD_BLOCK OSAL_EWOULDBLOCK
#define OSAL_ERR_INTERRUPTED OSAL_EINTR
#define OSAL_ERR_BAD_ADDRESS OSAL_EFAULT
#define OSAL_ERR_RESOURCE_LIMIT OSAL_EMFILE
#define OSAL_ERR_GENERIC OSAL_EIO
#define OSAL_ERR_INVALID_STATE 0xCB

const char *osal_get_status_name(int32_t status_code);

#endif /* OSAL_ERRNO_H */
