# SPDX-License-Identifier: GPL-2.0

pdm_core-y := pdm-core/core/pdm_core.o
pdm_core-y += pdm-core/core/pdm_chrdev.o
pdm_core-y += pdm-core/core/pdm_ctl.o
pdm_core-y += pdm-core/core/pdm_debugfs.o
pdm_core-y += pdm-core/core/pdm_proc.o
pdm_core-y += pdm-core/core/pdm_sysfs.o
