# =============================================================================
# Kconfig 集成模块
# =============================================================================
# 功能：读取 Kconfig 生成的 .config 文件，设置 CMake 变量
# 用法：include(cmake/Kconfig.cmake)
#       load_kconfig("${CMAKE_SOURCE_DIR}/.config")
# =============================================================================

# 函数：读取并解析 .config 文件
function(load_kconfig CONFIG_FILE)
    if(NOT EXISTS "${CONFIG_FILE}")
        message(FATAL_ERROR
            "Configuration file not found: ${CONFIG_FILE}\n"
            "\n"
            "Please run one of the following commands first:\n"
            "  make menuconfig           - Interactive configuration\n"
            "  make defconfig            - Load default configuration\n"
            "  make <board>_defconfig    - Load board-specific configuration\n"
            "\n"
            "Available defconfig files:\n"
        )
    endif()

    message(STATUS "Loading Kconfig configuration from ${CONFIG_FILE}")

    file(STRINGS "${CONFIG_FILE}" CONFIG_LINES)

    set(CONFIG_COUNT 0)

    foreach(LINE ${CONFIG_LINES})
        # 跳过注释和空行
        if(LINE MATCHES "^#" OR LINE STREQUAL "")
            continue()
        endif()

        # 解析 CONFIG_XXX=y
        if(LINE MATCHES "^CONFIG_([A-Z0-9_]+)=y")
            set(CONFIG_${CMAKE_MATCH_1} ON PARENT_SCOPE)
            message(STATUS "  CONFIG_${CMAKE_MATCH_1}=y")
            math(EXPR CONFIG_COUNT "${CONFIG_COUNT} + 1")
        endif()

        # 解析 CONFIG_XXX=n 或 # CONFIG_XXX is not set
        if(LINE MATCHES "^# CONFIG_([A-Z0-9_]+) is not set" OR
           LINE MATCHES "^CONFIG_([A-Z0-9_]+)=n")
            set(CONFIG_${CMAKE_MATCH_1} OFF PARENT_SCOPE)
        endif()

        # 解析 CONFIG_XXX="string"
        if(LINE MATCHES "^CONFIG_([A-Z0-9_]+)=\"(.*)\"")
            set(CONFIG_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}" PARENT_SCOPE)
            message(STATUS "  CONFIG_${CMAKE_MATCH_1}=\"${CMAKE_MATCH_2}\"")
            math(EXPR CONFIG_COUNT "${CONFIG_COUNT} + 1")
        endif()

        # 解析 CONFIG_XXX=123
        if(LINE MATCHES "^CONFIG_([A-Z0-9_]+)=([0-9]+)")
            set(CONFIG_${CMAKE_MATCH_1} ${CMAKE_MATCH_2} PARENT_SCOPE)
            message(STATUS "  CONFIG_${CMAKE_MATCH_1}=${CMAKE_MATCH_2}")
            math(EXPR CONFIG_COUNT "${CONFIG_COUNT} + 1")
        endif()
    endforeach()

    message(STATUS "Loaded ${CONFIG_COUNT} configuration options")
endfunction()

# 函数：将 Kconfig 配置导出为 C 宏定义
function(export_kconfig_to_c OUTPUT_FILE)
    message(STATUS "Generating ${OUTPUT_FILE}")

    file(WRITE "${OUTPUT_FILE}"
        "/* Auto-generated by CMake from Kconfig */\n"
        "#ifndef __KCONFIG_H__\n"
        "#define __KCONFIG_H__\n"
        "\n"
    )

    # 获取所有 CONFIG_* 变量
    get_cmake_property(VARS VARIABLES)
    foreach(VAR ${VARS})
        if(VAR MATCHES "^CONFIG_")
            if(${VAR})
                if(${VAR} STREQUAL "ON")
                    file(APPEND "${OUTPUT_FILE}" "#define ${VAR} 1\n")
                elseif(${VAR} MATCHES "^[0-9]+$")
                    file(APPEND "${OUTPUT_FILE}" "#define ${VAR} ${${VAR}}\n")
                else()
                    file(APPEND "${OUTPUT_FILE}" "#define ${VAR} \"${${VAR}}\"\n")
                endif()
            endif()
        endif()
    endforeach()

    file(APPEND "${OUTPUT_FILE}"
        "\n"
        "#endif /* __KCONFIG_H__ */\n"
    )
endfunction()
