# SPDX-License-Identifier: GPL-2.0

lpf_peripheral_runtime-y += lpf/config/src/lpf_config_api.o
lpf_peripheral_runtime-y += lpf/config/src/lpf_config_backend.o
lpf_peripheral_runtime-y += lpf/config/src/lpf_config_dt_backend.o
lpf_peripheral_runtime-y += lpf/config/src/lpf_config_dt_parser.o
lpf_peripheral_runtime-y += lpf/config/src/lpf_config_static_backend.o
lpf_peripheral_runtime-y += lpf/config/src/lpf_config_normalizer.o
lpf_peripheral_runtime-y += lpf/config/src/lpf_config_validator.o
lpf_peripheral_runtime-y += lpf/config/configs/lpf_config_configs.o
lpf_peripheral_runtime-y += lpf/config/configs/kernel/x86_modules/1.0.0/lpf_config_kernel_x86_modules.o
lpf_peripheral_runtime-y += lpf/config/configs/kernel/x86_mock_modules/1.0.0/lpf_config_kernel_x86_mock_modules.o
