# SPDX-License-Identifier: GPL-2.0

lpf_peripheral_runtime-y += lpf/peripheral/lpf_peripheral_module.o
lpf_peripheral_runtime-y += lpf/peripheral/lpf_peripheral.o
lpf_peripheral_runtime-y += lpf/peripheral/lpf_peripheral_config.o
lpf_peripheral_runtime-y += lpf/peripheral/lpf_peripheral_entry_start.o
